name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.HUB_DOCKER_USERNAME }}
          password: ${{ secrets.HUB_DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: . 
          push: true
          tags: hyp2nos/crm-app:1.0.${{ github.run_number }}
      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.5.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: Test SSH
      #   run: ssh valueit@valueit-OptiPlex-3040 "ls"

    
